### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by tangwenjing7** [cfangmeier/FTGenStudies#1]
I want to use it, but now I don’t know how to use it from the readme file. Can you tell me more about it?

**Comment by cfangmeier** [comment]
Hi @tangwenjing7, can you elaborate a bit more on what you are trying to do?

**Comment by tangwenjing7** [comment]
I want to identify structures that often appear in xml files. But I don't know what the format of the data your algorithm needs, and what are the steps to run it.thank u.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cfangmeier/FTGenStudies"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月31日(星期六) 凌晨0:20
收件人:&nbsp;"cfangmeier/FTGenStudies"<FTGenStudies@noreply.github.com&gt;;
抄送:&nbsp;"2923023500"<2923023500@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [cfangmeier/FTGenStudies] how to use it? (#1)





 
Hi @tangwenjing7, can you elaborate a bit more on what you are trying to do?

**Comment by cfangmeier** [comment]
This code doesn't do that. This code is for running different configurations of madgraph to perform measurements for particle physics.
